version: "2"

services:
  web:
    build: .
    command: nodemon -L --inspect=0.0.0.0:5858
    volumes:
      - .:/code
    ports:
      - "5000:5000"
      - "5858:5858"
    links:
      - mongo
    depends_on:
      - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet